name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            script_name: eval $(opam env) && make
            script_name2: ""
          - os: ubuntu-latest
            script_name: eval $(opam env) && make
            script_name2: ""
          - os: windows-latest
            # script_name: "$CYGWIN_ROOT\\bin\\bash"
            script_name: "D:\\cygwin\\bin\\bash"
            script_name2: eval $(opam env) && make

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Cache OCaml's opam
      uses: actions/cache@v2.1.5
      with:
        path: ~/.opam
        key: ${{matrix.os}}-latest-ocaml-4.06.1

    - name: Cache npm
      uses: actions/cache@v2.1.5
      with:
        path: ~/.npm
        key: ${{matrix.os}}-latest-node-14.4.0-${{hashFiles('package-lock.json')}}

    - name: Use OCaml
      uses: avsm/setup-ocaml@v1.1.10
      with:
        ocaml-version: 4.06.1

    - name: Use Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.4.0

    - run: npm install

    - run: opam pin add rescript-editor-support.dev . --no-action
    - run: opam install . --deps-only --with-doc --with-test
    - run: ${{matrix.script_name}}
    - run: ${{matrix.script_name2}}
